
/*

UPDATE  [SalesLT].[SalesOrderHeader]				SET [ModifiedDate] = DATEADD(MONTH, -3, GETDATE())
UPDATE  [SalesLT].[Address]							SET [ModifiedDate] = DATEADD(MONTH, -3, GETDATE())
UPDATE  [SalesLT].[Customer]						SET [ModifiedDate] = DATEADD(MONTH, -3, GETDATE())
UPDATE  [SalesLT].[CustomerAddress]					SET [ModifiedDate] = DATEADD(MONTH, -3, GETDATE())
UPDATE  [SalesLT].[Product]							SET [ModifiedDate] = DATEADD(MONTH, -3, GETDATE())
UPDATE  [SalesLT].[ProductCategory]					SET [ModifiedDate] = DATEADD(MONTH, -3, GETDATE())
UPDATE  [SalesLT].[ProductDescription]				SET [ModifiedDate] = DATEADD(MONTH, -3, GETDATE())
UPDATE  [SalesLT].[ProductModel]					SET [ModifiedDate] = DATEADD(MONTH, -3, GETDATE())
UPDATE  [SalesLT].[ProductModelProductDescription]	SET [ModifiedDate] = DATEADD(MONTH, -3, GETDATE())
UPDATE  [SalesLT].[SalesOrderDetail]				SET [ModifiedDate] = DATEADD(MONTH, -3, GETDATE())
UPDATE  [SalesLT].[SalesOrderHeader]				SET [ModifiedDate] = DATEADD(MONTH, -3, GETDATE())

*/



/*
UPDATE  [SalesLT].[SalesOrderHeader]				SET [ModifiedDate] = DATEADD(WEEK, -3, GETDATE())
UPDATE  [SalesLT].[Address]							SET [ModifiedDate] = DATEADD(WEEK, -3, GETDATE())
UPDATE  [SalesLT].[Customer]						SET [ModifiedDate] = DATEADD(WEEK, -3, GETDATE())
UPDATE  [SalesLT].[CustomerAddress]					SET [ModifiedDate] = DATEADD(WEEK, -3, GETDATE())
UPDATE  [SalesLT].[Product]							SET [ModifiedDate] = DATEADD(WEEK, -3, GETDATE())
UPDATE  [SalesLT].[ProductCategory]					SET [ModifiedDate] = DATEADD(WEEK, -3, GETDATE())
UPDATE  [SalesLT].[ProductDescription]				SET [ModifiedDate] = DATEADD(WEEK, -3, GETDATE())
UPDATE  [SalesLT].[ProductModel]					SET [ModifiedDate] = DATEADD(WEEK, -3, GETDATE())
UPDATE  [SalesLT].[ProductModelProductDescription]	SET [ModifiedDate] = DATEADD(WEEK, -3, GETDATE())
UPDATE  [SalesLT].[SalesOrderDetail]				SET [ModifiedDate] = DATEADD(WEEK, -3, GETDATE())
UPDATE  [SalesLT].[SalesOrderHeader]				SET [ModifiedDate] = DATEADD(WEEK, -3, GETDATE())

*/
